### ISSUE TITLE
TypeError: Cannot set property 'templateInput' of undefined

### ISSUE THREAD

**Issue by damianoferrari** [michaeldeboeve/generator-robonkey#5]
At the prompt "How would you like to create icons?", choosing "Not at all" causes the following error:

TypeError: Cannot set property 'templateInput' of undefined
    at createConfig (D:\dev\generator-robonkey\generators\app\config\writeConfig.js:219:49)
    at D:\dev\generator-robonkey\generators\app\config\writeConfig.js:15:7
    at D:\dev\generator-robonkey\generators\app\helpers\fileExists.js:18:9
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by michaeldeboeve** [comment]
thanks! fixed.
