### ISSUE TITLE
React removed from list of JS libraries

### ISSUE THREAD

**Issue by damianoferrari** [michaeldeboeve/generator-robonkey#6]
React is no longer available as an option when prompted for the JS libraries to include, although some references to React are still included in some of the files.

**Comment by michaeldeboeve** [comment]
yes, I did remove react. Should I re-enable it?

**Comment by damianoferrari** [comment]
To be honest, I discovered your generator because it included React. Since React is quite popular, I think it'd be nice to re-enable it (unless it creates problems with the other plugins).

**Comment by michaeldeboeve** [comment]
ok, I will include it, I don't know react that well, I guess that's why I removed it

**Comment by michaeldeboeve** [comment]
can you tell me which react scripts should be included?
I have:
react-dom-server.min.js
react-dom.min.js
react-with-addons.min.js
react.min.js

**Comment by michaeldeboeve** [comment]
I added react again

**Comment by damianoferrari** [comment]
I believe that reeact-dom (maybe react-dom-server) was recently taken out of react core library. I would probably include both.

**Comment by michaeldeboeve** [comment]
they're all in the react bower package, but main fails, according package.json are:  
"main": ["react.js", "react-dom.js"],

**Comment by michaeldeboeve** [comment]
done
